### ISSUE TITLE
Fit.DefinitionMessage:Unknown message number

### ISSUE THREAD

**Issue by jhavens12** [tcgoetz/Garmin#2]
When I run the garmin_connect_fit_to_xlsx.py file, I get a ton of error messages looking like this:

```
INFO:Fit.DefinitionMessage:Unknown message number 211: {'fields': 3, 'reserved': 0, 'architecture': 0, 'global_message_number': 211}
INFO:Fit.DefinitionMessage:Unknown message number 233: {'fields': 1, 'reserved': 0, 'architecture': 0, 'global_message_number': 233}
INFO:Fit.DefinitionMessage:Unknown message number 227: {'fields': 3, 'reserved': 0, 'architecture': 0, 'global_message_number': 227}
INFO:Fit.DefinitionMessage:Unknown message number 211: {'fields': 3, 'reserved': 0, 'architecture': 0, 'global_message_number': 211}
INFO:Fit.DefinitionMessage:Unknown message number 211: {'fields': 3, 'reserved': 0, 'architecture': 0, 'global_message_number': 211}
INFO:Fit.DefinitionMessage:Unknown message number 227: {'fields': 3, 'reserved': 0, 'architecture': 0, 'global_message_number': 227}
INFO:Fit.DefinitionMessage:Unknown message number 233: {'fields': 1, 'reserved': 0, 'architecture': 0, 'global_message_number': 233}
INFO:Fit.DefinitionMessage:Unknown message number 211: {'fields': 3, 'reserved': 0, 'architecture': 0, 'global_message_number': 211}
INFO:Fit.DefinitionMessage:Unknown message number 241: {'fields': 2, 'reserved': 0, 'architecture': 0, 'global_message_number': 241}
INFO:Fit.DefinitionMessage:Unknown message number 232: {'fields': 10, 'reserved': 0, 'architecture': 0, 'global_message_number': 232}
INFO:Fit.DefinitionMessage:Unknown message number 233: {'fields': 1, 'reserved': 0, 'architecture': 0, 'global_message_number': 233}
INFO:Fit.DefinitionMessage:Unknown message number 227: {'fields': 3, 'reserved': 0, 'architecture': 0, 'global_message_number': 227}
INFO:Fit.DefinitionMessage:Unknown message number 233: {'fields': 1, 'reserved': 0, 'architecture': 0, 'global_message_number': 233}
INFO:Fit.DefinitionMessage:Unknown message number 227: {'fields': 3, 'reserved': 0, 'architecture': 0, 'global_message_number': 227}
INFO:Fit.DefinitionMessage:Unknown message number 233: {'fields': 1, 'reserved': 0, 'architecture': 0, 'global_message_number': 233}
INFO:Fit.DefinitionMessage:Unknown message number 227: {'fields': 3, 'reserved': 0, 'architecture': 0, 'global_message_number': 227}
INFO:Fit.DefinitionMessage:Unknown message number 233: {'fields': 1, 'reserved': 0, 'architecture': 0, 'global_message_number': 233}
INFO:Fit.DefinitionMessage:Unknown message number 227: {'fields': 3, 'reserved': 0, 'architecture': 0, 'global_message_number': 227}
INFO:Fit.DefinitionMessage:Unknown message number 233: {'fields': 1, 'reserved': 0, 'architecture': 0, 'global_message_number': 233}
INFO:Fit.DefinitionMessage:Unknown message number 227: {'fields': 3, 'reserved': 0, 'architecture': 0, 'global_message_number': 227}
INFO:Fit.DefinitionMessage:Unknown message number 233: {'fields': 1, 'reserved': 0, 'architecture': 0, 'global_message_number': 233}
INFO:Fit.DefinitionMessage:Unknown message number 227: {'fields': 3, 'reserved': 0, 'architecture': 0, 'global_message_number': 227}
INFO:Fit.DefinitionMessage:Unknown message number 233: {'fields': 1, 'reserved': 0, 'architecture': 0, 'global_message_number': 233}
INFO:Fit.DefinitionMessage:Unknown message number 227: {'fields': 3, 'reserved': 0, 'architecture': 0, 'global_message_number': 227}
INFO:Fit.DefinitionMessage:Unknown message number 233: {'fields': 1, 'reserved': 0, 'architecture': 0, 'global_message_number': 233}
INFO:Fit.DefinitionMessage:Unknown message number 227: {'fields': 3, 'reserved': 0, 'architecture': 0, 'global_message_number': 227}

```

and then a final error at the end:

```
INFO:Garmin.GarminXlsxWriter:Creating 'garmin.xlsx'...
INFO:Garmin.GarminXlsxWriter:Writing sheet 'device'...
INFO:Garmin.GarminXlsxWriter:Writing sheet 'monitoring info'...
INFO:Garmin.GarminXlsxWriter:Writing sheet 'monitoring'...
Traceback (most recent call last):
  File "./garmin_connect_fit_to_xlsx.py", line 343, in <module>
    main(sys.argv[1:])
  File "./garmin_connect_fit_to_xlsx.py", line 339, in main
    gd.process_files(output_file)
  File "./garmin_connect_fit_to_xlsx.py", line 275, in process_files
    self.write_monitoring(gd_xlsx)
  File "./garmin_connect_fit_to_xlsx.py", line 181, in write_monitoring
    monitoring = Fit.MonitoringOutputData(self.fitfiles, self.sleep_period)
  File "/Users/Havens/Documents/GitHub/Garmin/Fit/MonitoringOutputData.py", line 42, in __init__
    OutputData.__init__(self, files)
  File "/Users/Havens/Documents/GitHub/Garmin/Fit/OutputData.py", line 15, in __init__
    self.parse()
  File "/Users/Havens/Documents/GitHub/Garmin/Fit/OutputData.py", line 19, in parse
    self.parse_messages(file)
  File "/Users/Havens/Documents/GitHub/Garmin/Fit/MonitoringOutputData.py", line 82, in parse_messages
    device = file.device()
  File "/Users/Havens/Documents/GitHub/Garmin/Fit/File.py", line 142, in device
    return self.product() + "_" + str(self.serial_number())
TypeError: unsupported operand type(s) for +: 'int' and 'str'

```
The output file is created but is unfinished, only the device, monitoring_info and monitoring sheets are added.

**Comment by tcgoetz** [comment]
I am no longer working on this project. You can achieve the same results with the GaminDB project. I will look into the issues you filed there.

**Comment by jhavens12** [comment]
Thanks!
